### ISSUE TITLE
有这个报错是因为什么啊

### ISSUE THREAD

**Issue by SevenO-o** [zhang-hai/apkjiagu#1]
Exception in thread "main" java.lang.UnsatisfiedLinkError: G:\jiagu\apkjiagu-master\jiagu\libs\sx_jiagu.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at com.zhh.jiagu.JiaGuMain.<clinit>(JiaGuMain.java:68)

**Comment by zhang-hai** [comment]
查找dll路径问题，没找到这个dll库。
看代码使用System.load()的地方有注释说明，我用的java 8用load方法加载正常
